
# This file tells Supabase about your Functions and Edge Functions.
# For more information, see: https://supabase.com/docs/guides/functions/quickstart

project_id = "ofwxyctfzskeeniaaazw"

[functions.generate-ai-content]
verify_jwt = true

[functions.debate]
verify_jwt = true
