
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "ofwxyctfzskeeniaaazw"
organization_id = "null"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# Maximum rows returns from a view, table, or stored procedure. Limits payload size for accidental
# large queries. Default is 1000.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (1
# week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Configure emails
[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Configure the service to send welcome emails and confirmations.
[auth.email.physical]
# Email address from which emails are going to be sent.
sender_name = "fake-email"
sender_address = "fake-sender@127.0.0.1"

# Use an external provider to send emails.
[auth.email.smtp]
sender_name = "fake-email"
sender_address = "fake-sender@127.0.0.1"
host = "127.0.0.1"
port = 54325
username = "supabase"
password = "supabase"
method = "plain"
# Use IPv6 to connect to host.
ipv6 = false
# Wait N milliseconds between sending emails.
ratelimit_burst = 5
ratelimit_interval = "1h"

[auth.email.template.invite]
subject = "You have been invited"
content_path = ""

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false

[auth.sms.twilio]
account_sid = ""
message_service_sid = ""
auth_token = ""

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Setup BigQuery project to send analytics events.
bq_project_id = ""
bq_dataset_id = ""
bq_table_id = ""

# Configure one of the supported email testing tools: awsses, mailgun, postmark, resend.
[email_testing]
provider = ""

[functions]
[functions.linkedin]
verify_jwt = true
