
project_id = "ofwxyctfzskeeniaaazw"

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe]
verify_jwt = true

[functions.twilio]
verify_jwt = true

[functions.postmark]
verify_jwt = true

[functions.heygen]
verify_jwt = true

[functions.shopify]
verify_jwt = true
