
project_id = "tnfqzklfdwknmplrygag"

[functions.academy-wins]
verify_jwt = false

[functions.strategy-templates]
verify_jwt = false

[functions.strategy-remix]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe]
verify_jwt = false

[functions.kpi-cron]
verify_jwt = false

[functions.send-weekly-digest]
verify_jwt = false
